/**
 * Builds client/public/sitemap.xml from the routes the app actually serves.
 *
 * The hand-maintained sitemap had drifted: five of the six service pages —
 * the highest commercial-intent URLs on the site — were missing, while
 * robots.txt explicitly allowed them. Generating it keeps the two in step.
 *
 *   node scripts/generate-sitemap.mjs
 *
 * Every entry is emitted twice, once per language, with reciprocal hreflang
 * alternates. /about is deliberately excluded: it renders the home page, so
 * listing it would be duplicate content.
 */
import fs from "node:fs";
import path from "node:path";

const ORIGIN = "https://foxsystemstech.com";
const OUT = path.join("client", "public", "sitemap.xml");
const ARTICLES_SRC = path.join("client", "src", "pages", "ArticleDetail.tsx");

const SOLUTIONS = ["medical-crm", "real-estate-crm", "pest-control-crm"];
// Keep in step with SERVICE_IDS in client/src/App.tsx. "software" was renamed
// to "crm" on 2026-09-24; leaving it here would have kept a redirecting URL in
// the sitemap, which wastes crawl budget and is flagged in Search Console.
const SERVICES = ["internet", "crm", "hardware", "cybersecurity", "infrastructure", "web-development"];
// Keep in step with TOOL_IDS in client/src/data/toolIds.ts.
const TOOLS = ["crm-cost-calculator"];

/** Read the article ids straight from the content map so the two can't diverge. */
function readArticleIds() {
  const source = fs.readFileSync(ARTICLES_SRC, "utf8");
  const ids = [...source.matchAll(/^ {2}"([a-z0-9-]+)":\s*\{/gm)].map(m => m[1]);
  if (ids.length === 0) throw new Error(`No article ids found in ${ARTICLES_SRC}`);
  return ids;
}

function buildRoutes() {
  const articles = readArticleIds();
  return [
    { path: "", changefreq: "weekly", priority: "1.0" },
    { path: "/services", changefreq: "weekly", priority: "0.9" },
    ...SERVICES.map(s => ({ path: `/services/${s}`, changefreq: "monthly", priority: "0.9" })),
    { path: "/solutions", changefreq: "monthly", priority: "0.9" },
    ...SOLUTIONS.map(s => ({ path: `/solutions/${s}`, changefreq: "monthly", priority: "0.9" })),
    { path: "/tools", changefreq: "monthly", priority: "0.8" },
    ...TOOLS.map(s => ({ path: `/tools/${s}`, changefreq: "monthly", priority: "0.8" })),
    { path: "/industries", changefreq: "monthly", priority: "0.8" },
    { path: "/case-studies", changefreq: "monthly", priority: "0.8" },
    { path: "/resources/it-guide", changefreq: "monthly", priority: "0.7" },
    { path: "/contact", changefreq: "monthly", priority: "0.8" },
    { path: "/articles", changefreq: "weekly", priority: "0.7" },
    ...articles.map(id => ({ path: `/articles/${id}`, changefreq: "monthly", priority: "0.6" })),
  ];
}

const enUrl = p => `${ORIGIN}${p === "" ? "/" : p}`;
const arUrl = p => `${ORIGIN}/ar${p}`;

function entry(loc, route, lastmod) {
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
    <xhtml:link rel="alternate" hreflang="en" href="${enUrl(route.path)}" />
    <xhtml:link rel="alternate" hreflang="ar" href="${arUrl(route.path)}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${enUrl(route.path)}" />
  </url>`;
}

const routes = buildRoutes();
const lastmod = new Date().toISOString().slice(0, 10);

const body = routes
  .flatMap(route => [entry(enUrl(route.path), route, lastmod), entry(arUrl(route.path), route, lastmod)])
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${body}
</urlset>
`;

fs.writeFileSync(OUT, xml);
console.log(`${routes.length * 2} URLs written to ${OUT}`);
